import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import Layout from '../components/Layout';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio | Lihueel Mansilla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Layout/>
    </div>
  )
}
